packages:
  - apps/*
  - packages/*
overrides:
  'js-yaml@>=4.0.0 <4.3.2': ^4.3.2
allowBuilds:
  argon2: true
  cpu-features: true
  esbuild: true
  ffmpeg-static: true
  msgpackr-extract: true
  msw: true
  protobufjs: true
  re2: true
  simple-git-hooks: true
  ssh2: true
  unrs-resolver: true
  vue-demi: true
